In [8]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
import project_path

import glob
import os
import random

from pathlib import Path
from itertools import product

import pandas as pd

In [10]:
def merge_csv(path_in, path_out):
    path_temp = Path(path_out).resolve()

    is_first_file = True    
    with open(path_temp,"wb") as output_file:
        for subdir, dirs, files in os.walk(path_in):
            for file in files:
                input_path = f'{subdir}/{file}'
                if is_first_file:
                    is_first_file = False
                    with open(input_path, "rb") as input_file:
                        output_file.write(input_file.read())
                else:
                    with open(input_path, "rb") as input_file:
                        next(input_file)
                        output_file.write(input_file.read())

In [11]:
pd.read_csv('../experiments.csv')

            id                   Type of experiment
0            0                    Local experiments
1   1587919855                            SBM (old)
2   1590579968                                  SBM
3   1590672352                     SBM test nb cuts
4   1590679038                 SBM 20 cuts keep 80%
5   1590585263                       Mindsets (old)
6   1590663805                             Mindsets
7   1590669671           Mindsets better resolution
8   1590676940   Mindsets better resolution 100-50%
9   1590680669       Mindsets better resolution 80%
10  1590686580             Mindsets 0->40 questions
11  1590636599                       cancer_10_bins
12  1590639814                       cancer_20_bins
13          11       2_gaussian_blobs_sigma_1_graph
14          10    2_gaussian_blobs_sigma_1.5_graph
15          12       4_gaussian_blobs_sigma_1_graph
16          13     4_gaussian_blobs_sigma_1.5_graph
17  1547845985     sbm 3 balanced sparse experiment
18  1547889898   sbm 3 unbalanced sparse experiment
19  1547847854     sbm 4 balanced sparse experiment
20  1547898989   sbm 4 unbalanced sparse experiment
21          14                                  LFR
22          15     2_gaussian_blobs_sigma_1_binning
23          16   2_gaussian_blobs_sigma_1.5_binning
24          17     4_gaussian_blobs_sigma_1_binning
25          18   4_gaussian_blobs_sigma_1.5_binning
26          20      2_gaussian_blobs_sigma_1_graph2
27          21    2_gaussian_blobs_sigma_1.5_graph2
28          22      4_gaussian_blobs_sigma_1_graph2
29          23    4_gaussian_blobs_sigma_1.5_graph2

In [18]:
experiment_id = '51'
path_in = Path(f'../output/{experiment_id}').resolve()
path_out = Path(f'../results/GaussMix_4_sig1_new.csv').resolve()
merge_csv(path_in, path_out)

In [19]:
df = pd.read_csv(path_out, index_col=0).reset_index(drop=True)
df

,seed,dataset_name,preprocessing_name,agreement,percentile_orders,unique_id,blob_sizes,blob_centers,k,sigma,nb_cuts,lb_f,Adjusted Rand Score
0,9,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.000085
1,1,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.006043
2,6,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,0.006861
3,4,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,0.005433
4,10,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.001525
5,5,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.004219
6,7,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.000727
7,2,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.000245
8,8,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.002873
9,3,gblobs,fid_mat,30,100,51,"[60, 60, 60, 60]","[[-2, -2], [-2, 2], [2, -2], [2, 2]]",24,1.5,30,0.2,-0.001189

In [17]:
df['Adjusted Rand Score'].mean().round(2), df['Adjusted Rand Score'].std().round(2)

(0.48, 0.14)

In [53]:
import src.loading

In [91]:
A, ys, _ = src.loading.load_LFR(nb_nodes=250,
                            tau1=3,
                            tau2=1.5,
                            mu=0.1,
                            average_degree=5,
                            min_community=20,
                            seed=10)

In [ ]:
import numpy as np

In [87]:
ys

array([1, 1, 1, 0, 1, 1, 1, 0, 2, 1, 1, 1, 2, 0, 0, 1, 2, 1, 2, 2, 0, 2,
       2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1,
       2, 2, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 2, 1, 0, 1, 0,
       1, 1, 1, 0, 2, 1, 0, 1, 1, 0, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 2, 0, 0])